sudo: false
language: php

php:
  - 5.6
  - nightly
  - hhvm

before_script:
  - composer self-update
  - if [ "$SF_EVT_DISPATCHER_VERSION" != "" ]; then composer require --no-update symfony/event-dispatcher:${SF_EVT_DISPATCHER_VERSION}; fi;
  - if [ "$SF_OPT_RESOLVER_VERSION" != "" ];   then composer require --no-update symfony/options-resolver:${SF_OPT_RESOLVER_VERSION};   fi;
  - composer install --no-interaction --prefer-source

script: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --verbose

matrix:
  include:
    - php: 7.2
      env: [SF_EVT_DISPATCHER_VERSION="^5.1", SF_OPT_RESOLVER_VERSION="^5.1"]
      
    - php: 7.3
      env: [SF_EVT_DISPATCHER_VERSION="^5.1", SF_OPT_RESOLVER_VERSION="^5.1"]
    
    - php: 7.4
      env: [SF_EVT_DISPATCHER_VERSION="^5.1", SF_OPT_RESOLVER_VERSION="^5.1"]

    - php: hhvm
      env: [SF_EVT_DISPATCHER_VERSION="^5.1", SF_OPT_RESOLVER_VERSION="^5.1"]

  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
